actress/urls.py
from django.urls import path
from . import views

app_name = "actress"
urlpatterns = [
        path("", views.index, name="index"),
        path("create", views.create_actress, name="create_actress"),
        path("cast_page<int:item>", views.cast_page, name="cast_page"),
        path("cast_edit<int:item>", views.cast_edit, name="cast_edit"),
        ]

day_sum/urls.py
from django.urls import path
from . import views

urlpatterns = [
        path("", views.main, name="main"),
        path("day_edit/<int:num>", views.day_edit, name="day_edit"),
        ]

django_app/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("day_sum/", include("day_sum.urls")),
    path("actress/", include("actress.urls"))
    ]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

actress/models.py
from django.db import models
from stdimage.models import StdImageField

#class Index(models.Model):
#    date = models.CharField("年月一覧",max_length=100)
#    def __str__(self):
#        return self.date
    
class Actress(models.Model):
    image = StdImageField(upload_to="media", blank=True, variations={
            "large": (600, 400),
            "thumbnail":(100,100,True),
            "medium":(300,200),
            })
#    image = models.ImageField(upload_to='images/', blank=True,null=True)
    no = models.IntegerField("ID",blank=True,null=True)
    name = models.CharField("名前",max_length=100,blank=True)#
    age = models.CharField("年齢",max_length=100,blank=True)#
    visit = models.CharField("住み",max_length=100,blank=True)#
    work = models.CharField("仕事",max_length=100,blank=True)#
    judgment = models.CharField("性格判定", max_length=100, null=True,blank=True )#
    hobby = models.CharField("趣味",max_length=100,blank=True)#
    birth = models.DateField("誕生日",null=True,blank=True)#
    co_date = models.DateField("記念日",null=True,blank=True)#
    my_date = models.CharField("伝えた誕生日", max_length=100, null=True, blank=True)
    career = models.TextField("経歴", null=True, blank=True)
    family = models.TextField("家族メモ", null=True, blank=True)
    date = models.DateField("LINE開始日",null=True,blank=True)#
    memo = models.TextField("メモ",blank=True)
    scenario = models.CharField("シナリオ",max_length=100,blank=True)
    car = models.BooleanField("車", null=True,blank=True)

    def __str__(self):
        return "{}".format(self.no)
    
    

day_sum/models.py
from django.db import models
import re

class Day_sum(models.Model):
    date = models.DateField()
    value = models.CharField(max_length=100)

    def __str__(self):
        #掛け算に対応してない→対応させるならif分岐
        sums = re.split("[+*]",self.value)
        return "<{0}> {1}円  {2}".format(self.date, sum([int(i) for i in sums]), self.id)

actress/forms.py
from django import forms
from .models import Actress
            
##アップロード場所
class CreateForm(forms.ModelForm):
    class Meta:
        model = Actress
        fields = \
        ["image","no","name","age","visit","work","hobby","birth","co_date","date","memo","scenario","judgment",\
         "my_date","family","career","car"]

day_sum/forms.py
from django import forms
from .models import Day_sum
from django.forms import Textarea
from django.core.files.storage import default_storage

class CreateForm(forms.ModelForm):
    class Meta:
        model = Day_sum
        fields = ["date", "value"]
        #widgets = {
            #"value":Textarea(attrs={"cols":80, "rows":20}),
            #}
            
            
##アップロード場所
#class UploadForm(forms.Form):
#    file = forms.FileField(label="CSVファイル")
#    
#    def save(self):
#        upload_file = self.cleaned_data["file"]
#        file_name = default_storage.save(upload_file.name, upload_file)
#        return default_storage.url(file_name)

actress/views.py
from django.shortcuts import render, redirect
from .models import Actress
from .forms import CreateForm
from django.contrib.auth.decorators import login_required


@login_required(login_url="/admin/login/")
def index(request):
    createform = CreateForm()
    data = Actress.objects.all()
    
    params = {
            "title":"index",
            "createform":createform,
            "data":data,
            }
    return render(request, "actress/index.html", params)

def create_actress(request):
    if(request.method == "POST"):
        createform = CreateForm(request.POST,request.FILES)
        createform.save()
        return redirect(to="/actress")
    
def cast_page(request, item):
    cast = Actress.objects.all().filter(no=item)
    params = {
            "title":"Cast",
            "data":cast,
            }
    return render(request, "actress/cast.html", params)

def cast_edit(request, item):
    cast = Actress.objects.all().filter(no=item).first()
    if (request.method=="POST"):
        form = CreateForm(request.POST, request.FILES, instance=cast)
        form.save()
        return redirect(to="/actress/cast_edit{}".format(item))
    
    params = {
            "title":"Cast",
            "data":cast,
            "form":CreateForm(instance=cast),
            }
    return render(request, "actress/edit.html", params)

day_sum/views.py
from django.shortcuts import render, redirect
from .models import Day_sum
from .forms import CreateForm
import re

def main(request):
    #金額部分を合計値に変換する関数→main.htmlに渡して表示
    def sums(sums_value):
        values = []
        for i in sums_value:
            ss = i.get("value")
            ss = re.split("[+*]", ss)
            values.append(sum([int(item) for item in ss]))
        return values


    #データのクリエイト部分
    if(request.method == "POST"):
        obj = Day_sum()
        form = CreateForm(request.POST, instance=obj)
        form.save()
        return redirect(to="/day_sum")
    
    
    
    all_data = Day_sum.objects.all()
    #全てのデータ
    #クエリデータの中の金額部分だけのデータ
    sums_value = all_data.values("value")
    #目標金額
    GOAL = 21000
    #期間
    DAYS = 30
    #一日あたり参考
    TODAY_GOAL = int(GOAL / DAYS)
    #データ個数
    COUNT = all_data.count()
    #合計
    sum_value = sum(sums(sums_value))
    #平均
    ave_value = int(sum_value / COUNT)
    #推移だよ
    tra_value = int(sum_value * DAYS)
    #一日あたりに使ってもいい金額
#    goal_value = int(TODAY_GOAL + ((TODAY_GOAL - ave_value) * COUNT))
    goal_value = int((GOAL - sum_value) / (DAYS - COUNT))
    #最新入力データ
    last_value = sums(sums_value)[-1]
    #残金
    bal_value = GOAL - sum_value
    
    
    
    
    #変数リスト
    result_list = {"sum_value":sum_value, "ave_value":ave_value, "tra_value":tra_value, \
                   "GOAL":GOAL, "TODAY_GOAL":TODAY_GOAL, "COUNT":COUNT, \
                   "last_value":last_value, "goal_value":goal_value, "bal_value":bal_value}


    
    params = {
            "title":"Todayマネー(ﾟ∀ﾟ　)",
            "data":all_data,
            "sums":sums(sums_value),
            "form":CreateForm(),
            "result_list":result_list,
#            "upload": UploadForm(),
            }
    return render(request, "day_sum/main.html", params)

def day_edit(request, num):
    obj = Day_sum.objects.get(id=num)
    if (request.method=="POST"):
        form = CreateForm(request.POST,instance=obj)
        form.save()
        return redirect(to="/day_sum")
    params = {
            "title":"Edit",
            "id":num,
            "form":CreateForm(instance=obj),
            }
    
    return render(request, "day_sum/day_edit.html", params)

actress/templates/actress/base.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'actress/css/style.css' %}" />
    <title>{{title}}</title>
</head>
<div class="container-fluid">
<h1>{{title}}</h1>
<nav class="navvar navbar-dark bg-dark">
    <td><a href="{% url 'actress:index' %}">メインページ</a></td>
</nav>

<body>
{% block header %}
{% endblock %}

{% block content %}
{% endblock %}

</body>
</div>
</html>

actress/templates/actress/cast.html
{% extends "actress/base.html" %}
{% load static%}
<link rel="stylesheet" type="text/css" href="{% static 'actress/css/style.css' %}">


{% block header %}
{% endblock %}
{% block content %}
<!--　プロフィール -->
    {% for item in data %}
    <div class="row">

        <div class="col-lg-2">
            {{item.no}}/
            {{item.name}}/
            {{item.judgment}}/
            {{data.image}}
            <img src="{{item.image.medium.url}}"><br>
            <a href= "{% url 'actress:cast_edit' item.no %}">edit</a>
<hr color="white">
        </div>

        <div class="col-lg-10">
            <table class="table border">
                <tr>
                    <th>ID</th>
                    <th>名前</th>
                    <th>年齢</th>
                    <th>誕生日</th>
                    <th>住み</th>
                    <th>仕事</th>
                    <th>趣味</th>
                    <th>車</th>
                    <th>記念日</th>
                    <th>LINE開始日</th>
                    <th>シナリオ</th>
                </tr>
                <tr>
                    <td>{{item.no}}</td>
                    <td>{{item.name}}</td>
                    <td>{{item.age}}</td>
                    <td>{{item.birth}}</td>
                    <td>{{item.visit}}</td>
                    <td>{{item.work}}</td>
                    <td>{{item.hobby}}</td>
                    <td>{{item.car|yesno:"あり,なし,不明"}}</td>
                    <td>{{item.co_date}}</td>
                    <td>{{item.date}}</td>
                    <td>{{item.scenario}}</td>
                </tr>
            </table>
<hr color="white">
        </div>
    </div>
<hr color="white">
    <div class="row">
        <div class="col-lg-5">
            メモ<br>
            {{item.memo | linebreaksbr}}
        </div>
        <div class="col-lg-5">
            経歴<br>
            {{item.career | linebreaksbr}}<br>
            <hr color="white">
            家族メモ<br>
            {{item.family | linebreaksbr}}<br>
        </div>
    </div>

    {% endfor %}
{% endblock %}

actress/templates/actress/edit.html
{% extends "actress/base.html" %}

{% block title %}Cast{% endblock %}

{% block header %}
<a href="{% url 'actress:cast_page' data.no %}">キャラページへ<a/>
{% endblock %}

{% block content %}

<table>
    <form enctype="multipart/form-data" action="{% url 'actress:cast_edit' data.no %}" method="post">
        {% csrf_token %}
        {{form.as_table}}
        <tr><td></td><td><input type="submit" value="編集"></td></tr>
    </form>
</table>

{% endblock %}

actress/templates/actress/index.html
{% extends "actress/base.html" %}

{% block title %}Index{% endblock %}

{% block header %}

<table>
    <tr>
        <form enctype="multipart/form-data" action="{% url 'actress:create_actress' %}", method="POST",>
        {%csrf_token%}
        {{createform.as_table}}
        <tr><td><input type="submit" value="登録"></td></tr>
        </form>
    </tr>
</table>

{% endblock %}

{% block content %}
<table class="table border">
    <tr>
        <th>Image</th>
        <th>ID</th>
        <th>名前</th>
        <th>年齢</th>
        <th>誕生日</th>
        <th>住み</th>
        <th>仕事</th>
        <th>趣味</th>
        <th>記念日</th>
        <th>LINE開始日</th>
        <th>シナリオ</th>
        <th></th>
        
    </tr>
        {% for item in data %}
    <tr>
        <td><img src="{{item.image.thumbnail.url}}"></td>
        <td><a href="{% url 'actress:cast_page' item %}">{{item.no}}<a/></td>
        <td>{{item.name}}</td>
        <td>{{item.age}}</td>
        <td>{{item.birth}}</td>
        <td>{{item.visit}}</td>
        <td>{{item.work}}</td>
        <td>{{item.hobby}}</td>
        <td>{{item.co_date}}</td>
        <td>{{item.date}}</td>
        <td>{{item.scenario}}</td>
        <td><a href= "{% url 'actress:cast_edit' item.no %}">edit</a>
    </tr>
        {% endfor %}
</table>

{% endblock %}

day_sum/templates/day_sum/create.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="{% static 'book/css/style.css' %}" />
</head>
<body>
    <h1>{{title}}</h1>
    <table>
        <form action="{% url 'create' %}" method="post">
        {% csrf_token %}
        {{ form.as_table }}
        <tr><td></td><td><input type="submit" value="登録"></td></tr>
        </form>
    </table>
</body>
</html>

day_sum/templates/day_sum/day_edit.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="{% static 'book/css/style.css' %}" />
</head>
<body>
    <h1>{{title}}</h1>
    <table>
        <form action="{% url 'day_edit' id %}" method="post">
        {% csrf_token %}
        {{ form.as_table }}
        <tr><td></td><td><input type="submit" value="登録"></td></tr>
        </form>
    </table>
</body>
</html>

day_sum/templates/day_sum/main.html
{% load static %}
{% load boost %}
<!doctype html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="{% static 'book/css/style.css' %}" />
</head>
<body>
    <h1>{{title}}</h1>
    <th>Count:</th>
        <td>{{result_list.COUNT}}<td>
        
        <form aciton="{% url 'main' %}" method="post">
        {% csrf_token %}
        {{form.as_table}}
        <tr></tr><tr><td><input type="submit" value="send"></td></tr>
        </form>
        
    <hr>
    
    <h2>目標金額:{{result_list.GOAL}}/1日:{{result_list.TODAY_GOAL}}</h2>
    <div class=today>
        最新記録:{{result_list.last_value}}<br>
        １日に使える金額:{{result_list.goal_value}}
    </div>

    <hr>
    <h2>DataBase</h2>
    <table>
        <tr>
            <th>合計</th>
            <th>平均</th>
            <th>推移</th>
            <th>残金</th>
            <th></th>
        </tr>
        <tr>
            <td>{{result_list.sum_value}}</td>
            <td>{{result_list.ave_value}}</td>
            <td>{{result_list.tra_value}}</td>
            <td>{{result_list.bal_value}}</td>
        </tr>
    </table>

    <table>
        <tr>
            <th>日付</th>
            <th>金額</th>
            <th>編集</th>
        </tr>
        {% for item, value in data|zip:sums %}
        <tr>
            <td>{{item.date}}</td>
            <td>{{value}}</td>
            <td><a href="{% url 'day_edit' item.id %}">edit</a></td>
        </tr>
        {% endfor %}
    </table>
</body>
</html>